"""initial schema

Revision ID: 4b47c8502fde
Revises: 
Create Date: 2026-08-10 22:12:18.651300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b47c8502fde'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_analyses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('region_hint', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('brief_json', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_content_analyses_created_at', 'content_analyses', ['created_at'], unique=False)
    op.create_index('ix_content_analyses_status', 'content_analyses', ['status'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('theme_text', sa.Text(), nullable=False),
    sa.Column('creator_name', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('aspect_ratio', sa.String(length=10), nullable=False),
    sa.Column('scene_overview', sa.Text(), nullable=True),
    sa.Column('storyboard_path', sa.Text(), nullable=True),
    sa.Column('final_video_path', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('reference_voice_shot_id', sa.Integer(), nullable=True),
    sa.Column('reference_voice_path', sa.Text(), nullable=True),
    sa.Column('auto_voice_calibrate', sa.Boolean(), nullable=False),
    sa.Column('content_analysis_id', sa.String(length=36), nullable=True),
    sa.Column('attached_brief_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_projects_created_at', 'projects', ['created_at'], unique=False)
    op.create_index('ix_projects_creator_name', 'projects', ['creator_name'], unique=False)
    op.create_index('ix_projects_status', 'projects', ['status'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('actor', sa.Text(), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_events_project_created', 'events', ['project_id', 'created_at'], unique=False)
    op.create_table('reference_images',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ref_images_project_kind_order', 'reference_images', ['project_id', 'kind', 'order_index'], unique=False)
    op.create_table('reference_samples',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('analysis_id', sa.String(length=36), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('video_path', sa.Text(), nullable=False),
    sa.Column('audio_path', sa.Text(), nullable=True),
    sa.Column('has_speech', sa.Boolean(), nullable=True),
    sa.Column('hook_text', sa.Text(), nullable=True),
    sa.Column('full_transcript', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['content_analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reference_samples_analysis', 'reference_samples', ['analysis_id'], unique=False)
    op.create_table('shots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('shot_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('shot_type', sa.String(length=50), nullable=False),
    sa.Column('visual_description', sa.Text(), nullable=False),
    sa.Column('shot_duration', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('align_with_previous', sa.Boolean(), nullable=False),
    sa.Column('use_prev_last_frame', sa.Boolean(), nullable=False),
    sa.Column('motion_prompt', sa.Text(), nullable=True),
    sa.Column('video_path', sa.Text(), nullable=True),
    sa.Column('last_frame_path', sa.Text(), nullable=True),
    sa.Column('veo_operation_id', sa.Text(), nullable=True),
    sa.Column('word_count_warning', sa.Boolean(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('custom_first_frame_path', sa.Text(), nullable=True),
    sa.Column('ff_status', sa.String(length=20), nullable=True),
    sa.Column('ff_error_message', sa.Text(), nullable=True),
    sa.Column('custom_reference_paths', sa.Text(), nullable=True),
    sa.Column('reference_image_hint', sa.Text(), nullable=True),
    sa.Column('vc_status', sa.String(length=20), nullable=True),
    sa.Column('vc_error_message', sa.Text(), nullable=True),
    sa.Column('cc_status', sa.String(length=20), nullable=True),
    sa.Column('cc_error_message', sa.Text(), nullable=True),
    sa.Column('target_last_frame_path', sa.Text(), nullable=True),
    sa.Column('tf_status', sa.String(length=20), nullable=True),
    sa.Column('tf_error_message', sa.Text(), nullable=True),
    sa.Column('tf_confirmed', sa.Boolean(), nullable=True),
    sa.Column('auto_trim', sa.Boolean(), nullable=False),
    sa.Column('trim_frames', sa.Integer(), nullable=True),
    sa.Column('source_fps', sa.Float(), nullable=True),
    sa.Column('source_frames', sa.Integer(), nullable=True),
    sa.Column('vc_audio_path', sa.Text(), nullable=True),
    sa.Column('audio_head_mute_frames', sa.Integer(), nullable=True),
    sa.Column('pre_cc_last_frame_key', sa.Text(), nullable=True),
    sa.Column('pristine_last_frame_key', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'shot_id', name='uq_shot_project_shot_id')
    )
    op.create_index('ix_shots_project_shot_id', 'shots', ['project_id', 'shot_id'], unique=False)
    op.create_index('ix_shots_project_status', 'shots', ['project_id', 'status'], unique=False)
    op.create_table('image_candidates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('shot_pk', sa.Integer(), nullable=False),
    sa.Column('shot_id', sa.Integer(), nullable=False),
    sa.Column('slot', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('prompt_source', sa.String(length=10), nullable=False),
    sa.Column('custom_prompt', sa.Text(), nullable=True),
    sa.Column('ref_paths', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('adopted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shot_pk'], ['shots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_image_candidates_shot', 'image_candidates', ['project_id', 'shot_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_image_candidates_shot', table_name='image_candidates')
    op.drop_table('image_candidates')
    op.drop_index('ix_shots_project_status', table_name='shots')
    op.drop_index('ix_shots_project_shot_id', table_name='shots')
    op.drop_table('shots')
    op.drop_index('ix_reference_samples_analysis', table_name='reference_samples')
    op.drop_table('reference_samples')
    op.drop_index('ix_ref_images_project_kind_order', table_name='reference_images')
    op.drop_table('reference_images')
    op.drop_index('ix_events_project_created', table_name='events')
    op.drop_table('events')
    op.drop_index('ix_projects_status', table_name='projects')
    op.drop_index('ix_projects_creator_name', table_name='projects')
    op.drop_index('ix_projects_created_at', table_name='projects')
    op.drop_table('projects')
    op.drop_index('ix_content_analyses_status', table_name='content_analyses')
    op.drop_index('ix_content_analyses_created_at', table_name='content_analyses')
    op.drop_table('content_analyses')
    # ### end Alembic commands ###
